# Import Required Libraries

In [115]:
# Standard useful data processing imports
import random
import numpy as np
import pandas as pd
import csv
# Visualisation imports
import matplotlib.pyplot as plt
import seaborn as sns
# Scikit learn for preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MultiLabelBinarizer
# Keras Imports - CNN
from keras.models import Sequential
from keras.layers import Dense, Conv2D, MaxPool2D, Flatten, Dropout
from keras.optimizers import Adam
from keras.utils.np_utils import to_categorical

# Model MK1

In [117]:
# use multilabels
labels = np.loadtxt(open('/home/rodrigo/Projects/TCC/labels-merged.csv', "rb"), delimiter=",", skiprows=1)
labels2 = MultiLabelBinarizer().fit_transform(labels)

[[  0.   0.   0. ...   0.   0.   0.]
 [  1.   1.   1. ...   0.   0.   1.]
 [  2.   0.   0. ...   0.   0.   0.]
 ...
 [488.   1.   1. ...   0.   0.   1.]
 [489.   1.   0. ...   0.   0.   1.]
 [490.   0.   0. ...   0.   0.   0.]]
[[1 0 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 ...
 [1 1 0 ... 1 0 0]
 [1 1 0 ... 0 1 0]
 [1 0 0 ... 0 0 1]]


# Read Label File

In [112]:
# path = '/home/rodrigo/Projects/TCC/'
# file = 'labels2.csv'
# labels = np.loadtxt(open(path + file, "rb"), delimiter=",", skiprows=1)
# exams = labels[:, 0]
# ich = [ int(x/2) for x in np.sum(labels[:,1:4], axis=1) ]
# iph = [ int(x/2) for x in np.sum(labels[:,4:7], axis=1)]
# ivh = [ int(x/2) for x in np.sum(labels[:,7:10], axis=1)]
# sdh = [ int(x/2) for x in np.sum(labels[:,10:13], axis=1)]
# edh = [ int(x/2) for x in np.sum(labels[:,13:16], axis=1)]
# sah = [ int(x/2) for x in np.sum(labels[:,16:19], axis=1)]
# result = np.transpose(np.matrix([exams, ich, iph, ivh, sdh, edh, sah]))
# np.savetxt(path + 'labels-merged.csv', result, delimiter=",")